# example values

indexing:
 settings:
  sites:
   - url: "https://lenta.ru/"
     name: lenta
   - url: "https://www.sports.ru/"
     name: sports
 http:
   user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
   referrer: "https://www.google.com"
   timeout: 3000

server:
  port: 8080
  tomcat:
    connection-timeout: 30s

spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE